# Generated by Django 4.0 on 2021-12-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('municipality_code', models.IntegerField(verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('state_code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('settlement_type', models.CharField(max_length=30, verbose_name='Settlement type')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
                ('zone_type', models.CharField(max_length=20, verbose_name='Zone type')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipcodes.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Suburb',
                'verbose_name_plural': 'Suburbs',
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipcodes.state', verbose_name='State'),
        ),
    ]
