# Generated by Django 4.0 on 2021-12-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
