# Generated by Django 4.0 on 2021-12-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0002_state_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='suburb',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
